// <auto-generated />
using System;
using FitBot.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FitBot.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FitBot.Api.Models.BmiLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float>("BmiValue")
                        .HasColumnType("real")
                        .HasColumnName("bmivalue");

                    b.Property<DateTime>("DateRecorded")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("daterecorded");

                    b.Property<float>("Height")
                        .HasColumnType("real")
                        .HasColumnName("height");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("userid");

                    b.Property<float>("Weight")
                        .HasColumnType("real")
                        .HasColumnName("weight");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("bmilogs");
                });

            modelBuilder.Entity("FitBot.Api.Models.ChatHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sessionid");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("userid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("chathistories");
                });

            modelBuilder.Entity("FitBot.Api.Models.ChatMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsBot")
                        .HasColumnType("boolean")
                        .HasColumnName("isbot");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("userid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("chathistory", (string)null);
                });

            modelBuilder.Entity("FitBot.Api.Models.DeepMemory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<string>("MemoryKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("memorykey");

                    b.Property<string>("MemoryValue")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("memoryvalue");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedat")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("userid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "MemoryKey")
                        .IsUnique();

                    b.ToTable("deepmemories");
                });

            modelBuilder.Entity("FitBot.Api.Models.DietPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("NOW()");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("isactive");

                    b.Property<string>("PlanJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("planjson");

                    b.Property<string>("PlanType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("plantype");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("userid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("dietplans");
                });

            modelBuilder.Entity("FitBot.Api.Models.ExercisePlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("NOW()");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("isactive");

                    b.Property<string>("PlanJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("planjson");

                    b.Property<string>("SplitType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("splittype");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("userid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("exerciseplans");
                });

            modelBuilder.Entity("FitBot.Api.Models.LikedVideo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("LikedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("likedat")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("text")
                        .HasColumnName("thumbnailurl");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("userid");

                    b.Property<string>("VideoId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("videoid");

                    b.Property<string>("YoutubeUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("youtubeurl");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "VideoId")
                        .IsUnique();

                    b.ToTable("likedvideos");
                });

            modelBuilder.Entity("FitBot.Api.Models.ReferenceMotion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<string>("ExerciseName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("exercisename");

                    b.Property<string>("FramesDataJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("framesdatajson");

                    b.Property<string>("MotionPatternJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("motionpatternjson");

                    b.Property<int>("TotalFramesProcessed")
                        .HasColumnType("integer")
                        .HasColumnName("totalframesprocessed");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedat");

                    b.Property<int>("VideoId")
                        .HasColumnType("integer")
                        .HasColumnName("videoid");

                    b.Property<string>("VideoMetadataJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("videometadatajson");

                    b.HasKey("Id");

                    b.HasIndex("VideoId");

                    b.ToTable("referencemotions");
                });

            modelBuilder.Entity("FitBot.Api.Models.StopWord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("word");

                    b.HasKey("Id");

                    b.ToTable("stopwords");
                });

            modelBuilder.Entity("FitBot.Api.Models.Synonym", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsNew")
                        .HasColumnType("boolean")
                        .HasColumnName("isnew");

                    b.Property<string>("Keyword")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("keyword");

                    b.Property<string>("SynonymsRaw")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("synonymsraw");

                    b.HasKey("Id");

                    b.ToTable("synonyms");
                });

            modelBuilder.Entity("FitBot.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("passwordhash");

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("text")
                        .HasColumnName("passwordresettoken");

                    b.Property<DateTime?>("PasswordResetTokenExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("passwordresettokenexpiresat");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("FitBot.Api.Models.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("integer")
                        .HasColumnName("age");

                    b.Property<float>("BmiValue")
                        .HasColumnType("real")
                        .HasColumnName("bmivalue");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("gender");

                    b.Property<string>("HealthIssues")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("healthissues");

                    b.Property<float>("Height")
                        .HasColumnType("real")
                        .HasColumnName("height");

                    b.Property<bool>("IsBmiFromAi")
                        .HasColumnType("boolean")
                        .HasColumnName("isbmifromai");

                    b.Property<float>("TargetWeight")
                        .HasColumnType("real")
                        .HasColumnName("targetweight");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("userid");

                    b.Property<float>("Weight")
                        .HasColumnType("real")
                        .HasColumnName("weight");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("userprofiles");
                });

            modelBuilder.Entity("FitBot.Api.Models.Video", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("link");

                    b.Property<string>("TagsRaw")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tagsraw");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.ToTable("videos");
                });

            modelBuilder.Entity("FitBot.Api.Models.VideoMotionPattern", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ExerciseName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("exercisename");

                    b.Property<double>("Fps")
                        .HasColumnType("double precision")
                        .HasColumnName("fps");

                    b.Property<string>("FramesJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("framesjson");

                    b.Property<string>("MotionPatternJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("motionpatternjson");

                    b.Property<DateTime>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processedat");

                    b.Property<int>("TotalFrames")
                        .HasColumnType("integer")
                        .HasColumnName("totalframes");

                    b.Property<int>("VideoId")
                        .HasColumnType("integer")
                        .HasColumnName("videoid");

                    b.HasKey("Id");

                    b.HasIndex("VideoId");

                    b.ToTable("videomotionpatterns");
                });

            modelBuilder.Entity("FitBot.Api.Models.BmiLog", b =>
                {
                    b.HasOne("FitBot.Api.Models.User", "User")
                        .WithMany("BmiLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitBot.Api.Models.ChatHistory", b =>
                {
                    b.HasOne("FitBot.Api.Models.User", "User")
                        .WithMany("ChatHistories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitBot.Api.Models.ChatMessage", b =>
                {
                    b.HasOne("FitBot.Api.Models.User", "User")
                        .WithMany("ChatHistory")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitBot.Api.Models.DeepMemory", b =>
                {
                    b.HasOne("FitBot.Api.Models.User", "User")
                        .WithMany("DeepMemories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitBot.Api.Models.DietPlan", b =>
                {
                    b.HasOne("FitBot.Api.Models.User", "User")
                        .WithMany("DietPlans")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitBot.Api.Models.ExercisePlan", b =>
                {
                    b.HasOne("FitBot.Api.Models.User", "User")
                        .WithMany("ExercisePlans")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitBot.Api.Models.LikedVideo", b =>
                {
                    b.HasOne("FitBot.Api.Models.User", "User")
                        .WithMany("LikedVideos")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitBot.Api.Models.ReferenceMotion", b =>
                {
                    b.HasOne("FitBot.Api.Models.Video", "Video")
                        .WithMany()
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Video");
                });

            modelBuilder.Entity("FitBot.Api.Models.UserProfile", b =>
                {
                    b.HasOne("FitBot.Api.Models.User", "User")
                        .WithOne("Profile")
                        .HasForeignKey("FitBot.Api.Models.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitBot.Api.Models.VideoMotionPattern", b =>
                {
                    b.HasOne("FitBot.Api.Models.Video", "Video")
                        .WithMany()
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Video");
                });

            modelBuilder.Entity("FitBot.Api.Models.User", b =>
                {
                    b.Navigation("BmiLogs");

                    b.Navigation("ChatHistories");

                    b.Navigation("ChatHistory");

                    b.Navigation("DeepMemories");

                    b.Navigation("DietPlans");

                    b.Navigation("ExercisePlans");

                    b.Navigation("LikedVideos");

                    b.Navigation("Profile");
                });
#pragma warning restore 612, 618
        }
    }
}
